default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: quanzhanying-1

test:
  <<: *default
  database: quanzhanying-1

production:
  <<: *default
  database: quanzhanying-1
